server:
  port: 9999
  context-path: /CMFZ
  jsp-servlet:
    init-parameters:
      development: true
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cmfz?useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: hr
  mvc:
    view:
      suffix: .jsp
      prefix: /
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd
  application:
    name: kingboy-springboot-file
  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb
mybatis:
  mapper-locations: classpath:mapper/*DaoMapper.xml